### PR TITLE
feat(camera):include iris aperture controls

### PR DESCRIPTION
**Pull request by polonski**
- [x] adding iris controls to the camera interface

### CODE REVIEW

**Comment by stakach** [comment]
I'm not sure we want this standardised as most cameras have auto-focus / auto-exposure
and where it is possible to set manually, almost no one uses it

So I think we're reasonably safe not adding this complexity to the interface as anyone requiring manual exposure adjustment will require a custom interface anyway.

**Comment by polonski** [comment]
This is specifically for the Wolfvision eye14 camera which has distinct iris aperture controls

**Comment by stakach** [comment]
you can implement them in the driver without requiring an interface for those controls
I would seperate them from the `move` function too, the move function is there for panning primarily.

If anything I would flip it and have the `move` function call map to the `iris` function (I think `adjust` isn't descriptive enough)

**Comment by polonski** [comment]
ok

**Pull request closed without merging**
